### ISSUE TITLE
Bounding Boxes are cut in half

### ISSUE THREAD

**Issue by MarcoXAvante** [CITM-UPC/AV-Mace_Engine#2]
Hello Pep, we have been working on frustum culling and bounding boxes and our boxes are appearing in the correct place but somehow cut in half. We don't understand why this is happening. Can you help us?

**Comment by pepcots** [comment]
Hello @MarcoXAvante , I can't see where are you initializing the bounding boxes?
GameObject::setBoundingBox method has no references

**Comment by joanmarquesbesses** [comment]
Hello Pep, we are creating the bounding boxes in ModelLoader.cpp in the graphicObjectFromNode function.
![image](https://github.com/user-attachments/assets/c990ecde-864c-4e28-8454-3221bafdc6ad)

**Comment by MarcoXAvante** [comment]
@pepcots We managed to fix the bounding boxes, but now we have an issue when loading the city:
The extra transforms that assimp takes into account when loading the fbx are created as entire new nodes, and we can't get them to not be taken into account when building those bounding boxes. If we make a "obj.hascomponent<mesh>" check the program thinks they do have a mesh. What can we do to avoid having these transformations in the hierarchy and also to not have their fake bounding boxes?
![image](https://github.com/user-attachments/assets/2ef1c558-61a8-4e73-9942-20fb18266f86)
![image](https://github.com/user-attachments/assets/9a55c6fd-eb0c-400d-8a7a-3d7f687e27dc)

**Comment by pepcots** [comment]
Why does the "hasComponent<Mesh>()" returns true for an object that does not have a mesh?

**Comment by MarcoXAvante** [comment]
We saw the issue: We were checking all the time for the mesh of the child, not itself. We fixed it and now it seems the bounding boxes for each house works properly, we need to finish the global bounding box.

**Comment by MarcoXAvante** [comment]
Our bounding boxes work as expected now.
